slug = "rolls-1"
title = "Rolls 1"
author = "Jerry"
value = 15
description = """A new [sushi place](rolls1) has opened up in your neighborhood, and you are curious to check it out. However, only once inside the restaurant do you realize that the place was more expensive than expected, and you seem to have forgotten your wallet."""
tags = ["binary"]
files = ["rolls1"]
flag = "flag{california_rolls_are_sushi}"
enabled = true