id = 8
title = "Cyber Academy: Binary Exploitation 2"
short = "Binary Exploitation" 
date = "Wednesday 5/4 6:00PM-8:00PM PT"
description = """Cyber Academy’s Binary Exploitation was so good, we decided to make a second one! Come on down to our final workshop of the quarter this week to have even more fun and learn even more about buffer overflows! We’ll be going over advanced
techniques like return-oriented programming and gadgets so you can find out everything you’ll ever want to know about binary exploits for the rest of your life! (and *ahem* for the attack lab).

Zoom Link: [https://ucla.zoom.us/j/94178019377](https://ucla.zoom.us/j/94178019377)
"""
link = "https://fb.me/e/31IFXe0nH"
slides = "http://links.uclaacm.com/binaryexploitation2 "
