id = 5
title = "CTF After Dark"
short = "CTF After Dark" 
date = "Wednesday 5/18 6:00PM-8:00PM PT"
description = """Here it is, the moment you’ve all been waiting for! For the past 8 weeks-- morning, noon, and night-- you’ve been training tirelessly.
You know it all: assembly, reverse engineering, buffer overflow, and it’s finally time to put your skills and hard work to use, and kick some binary booty!
CTF After Dark will kick off at 6:00 pm on Wednesday, May 11 at Bunche Hall 3211, and will last until 6:00 pm the following Wednesday (May 18).
There will be prizes for the winners!

Zoom Link: [https://ucla.zoom.us/j/94178019377](https://ucla.zoom.us/j/94178019377)
"""
link = ""
slides = ""
