id = 7
title = "Cyber Social #2: Cyber Sawtelle Special"
short = "Sawtelle Special" 
date = "Friday 5/27 6:00PM PT"
description = """After Cyber Academy, CTF After Dark, and almost all of Spring Quarter… you’ve done it! You’ve made it through! 😩 Now it’s time to celebrate with the #1 cyber crew! 😎 Join us for the ultimate cyber party as we take a trip to Sawtelle! 🎉 We’ll be socializing to destress after a long quarter (and year) and celebrating a successful quarter! 🥳 Meet us at TBD on Friday, May 27th, 2022 at 6pm. Hope to see you all there!
"""
link = ""
slides = ""
